### ISSUE TITLE
oasp template is not listed/available while creating maven project.

### ISSUE THREAD

**Issue by razadfki** [themetalone/oomph-server#1]
after successful installation of IDE, I am following this tutorial [https://github.com/oasp/oasp4j/wiki/tutorial-newapp](url) but unfortunately I cannot locate the oasp template for my maven project which should be like the following link: [https://raw.githubusercontent.com/wiki/oasp/oasp4j/images/maven-archetype.png](url) but what I am getting is this 

![oasp](https://cloud.githubusercontent.com/assets/18569477/14997171/9b4002c4-117d-11e6-867f-4c7d08ac2bfe.JPG)
**additionally, installer report looks OK.**
![report](https://cloud.githubusercontent.com/assets/18569477/14997236/eefffca2-117d-11e6-9924-7ea4517be0db.JPG)

**Am I missing something or doing something wrong?**
Need your help. Thanks!

**Comment by themetalone** [comment]
I actually cannot tell you if you did something wrong but my pre-eclipse-installer version of the OASP4J IDE produces the same. I'll try to find a solution.

In the mean time simply use the 'From Console' instructions (and don't forget to exchange 'simpleapp' with your apps name in the command).

**Comment by razadfki** [comment]
Thanks for the quick response! I will follow the cmd instructions now.

**Comment by themetalone** [comment]
Hello @razadfki 

This problem occured on 'normal' installations of the OASP4J IDE also. It doesn't seems related to the setup file.

**Comment by razadfki** [comment]
yeah! okay.
by the way, I used the Console instructions which worked flawlessly.
